apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv

spec:
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgresql

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: grs-databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi