apiVersion: apps/v1
kind: Deployment
metadata:
  name: soap-api
  namespace: jmmg-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piezas-api
  template:
    metadata:
      labels:
        app: piezas-api
    spec:
      containers:
        - name: piezas-api
          image: localhost:5000/piezas-api:1
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: piezas-api-secrets
                  key: connection-string
          ports:
            - containerPort: 8080