apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientes-api
  namespace: jmmg-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientes-api
  template:
    metadata:
      labels:
        app: clientes-api
    spec:
      containers:
        - name: clientes-api
          image: localhost:5000/clientes-api:1
          env:
            - name: "UserServiceEndpoint"
              value: "http://piezas-api-svc.jmmg-backend-api.svc.cluster.local:8080/PiezaService.svc"
            - name: "MongoDB__clientes__ConnectionString"
              valueFrom:
                secretKeyRef:
                  name: clientes-api-secrets
                  key: connection-string
          ports: 
            - containerPort: 3000