apiVersion: v1
kind: Service
metadata:
  name: clientes-api-svc
  namespace: jmmg-backend-api
spec:
  type: LoadBalancer
  ports: 
    - port: 3000
      targetPort: 3000
  selector:
    app: clientes-api